name: flutter_architecture_sample
description: FlutterKaigi 2022「アプリの安全な変化と拡大を支えるアーキテクチャと単体テスト」のためのサンプルアプリ
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
