name: web
on:
  push:
    branches:
      - main
  # プルリクの作成と更新
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Firebase CLIをインストールする
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g firebase-tools
      # Flutter環境のセットアップ
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
          cache: true
      # 依存ライブラリのダウンロード
      - run: flutter pub get
      # freezedのためにbuild_runnerの実行
      - run: flutter pub run build_runner build
      # Build release build
      - run: flutter build web
      # Deploy to Firebase hosting
      - run: firebase deploy  --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:fas
